# Preload the wallpaper into memory
preload = /modules/hypr/wallpapers/mywall.jpg

# Apply the same wallpaper to all monitors
wallpaper = ,/modules/hypr/wallpapers/mywall.jpg

# Disable IPC if you don’t need runtime changes
ipc = off
